name: Hello push
on: workflow_dispatch
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git clone https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} repo
        cd repo
        date > hello.txt
        git add .
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git commit -m hello
        git push
